#########################################################################
#       This script plots the diffusion tensor of the                   #
#       magnetic fields generated by generate_samples.exe               #
#                                                                       #
#       Written by                              #
#########################################################################

import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.colors import Normalize

d_i = np.loadtxt('Data/Ee18_LM150/eigenvalues.dat') 

#d_i = np.delete(d_i, [0, 1], 0)

#print(d_i)

i = len(d_i)
#print(i)

t = []

l = 1
k = 0
for a in range(0, i):
    t.append(l * 10**k)                     # t now holds the time-vector to plot the values against.
    if(l == 9):
        l = 1
        k = k + 1
    else:
        l = l + 1




fig1 = plt.figure(1)

plt.title(r'Diffusion tensor, $L_{max} = 10 \mathrm{pc}$')
plt.xlabel('Time in years')
plt.ylabel(r'$ \mathrm{D}($ $[ \mathrm{cm}^2 / \mathrm{s}]$')

for k in range(0, 3):
    plt.loglog(t, 3.019 * 10 ** 29 * d_i[:,k], linestyle='-')

plt.loglog(t, 3.019 * 10 ** 29 * d_i[:,3], linestyle='--', color='black')

plt.legend(('$d_1$', '$d_2$', '$d_3$'))

plt.show()
